
name: Build and Test
on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        use-ros2-testing: true
        install-connext: false
        required-ros-distributions: humble
    - name: Checkout repository    
      uses: actions/checkout@v4
    - name: Build 
      run: |
        cd dev_ws
        source /opt/ros/humble/setup.bash
        colcon build
        colcon test --packages-select sample --event-handlers console_direct+
    - name: Run Tests
      run: |
        cd dev_ws/build/sample
        ./sample_test
