
name: Build and Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.4.1
      with:
        use-ros2-testing: true
        install-connext: false
        required-ros-distributions: foxy
    - name: Checkout repository    
      uses: actions/checkout@v3
    - name: Build 
      run: |
        cd dev_ws
        source /opt/ros/foxy/setup.bash
        colcon build
        colcon test --packages-select sample --event-handlers console_direct+
    - name: Run Tests
      run: |
        cd dev_ws/build/sample
        ./sample_test
